services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "y"
      MSSQL_PID: "Express"
      SA_PASSWORD: "Pa55Word!" 
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 5s
      timeout: 2s
      retries: 10
  api:
    build:
      context: .
      dockerfile: "TaskOrganizer.Api/Dockerfile"
    environment:
       - "ConnectionStrings:Default=Server=db,1433;Initial Catalog=TasksDb;User ID=SA;Password=Pa55Word!"
    ports:
      - "8080:80"
    expose:
      - "80"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 5s
      timeout: 2s
      retries: 10
  app:
    build:
      context: .
      dockerfile: "TaskOrganizer.AppServer/Dockerfile"
    environment:
      - "ApiBaseUri=http://api:80/api/"
      - "TasksApiBaseUri=http://api:80/api/tasks/"
      - "TaskBoardsApiBaseUri=http://api:80/api/taskboards/"
    ports:
      - "7070:80"
    expose:
      - "80"
    depends_on:
      api:
        condition: service_healthy
    
